spring.application.name=ch12-ex1
custom.datasource.url=jdbc:mysql://localhost:3306/custom_demo_db
useLegacyDatetimeCode=false&serverTimezone=UTC
custom.datasource.username=custom_user
custom.datasource.password=custom_password
spring.sql.init.mode=always
