spring.application.name=ch12-mySQL
spring.datasource.url=jdbc:mysql://localhost:3306/spring_demo_db
spring.datasource.username=demo_user
spring.datasource.password=demo_password
spring.sql.init.mode=always